some_log_value1: air-slurp.wav
some_log_value2: boink.wav
some_log_value3: high-zoom.wav
some_log_value4: ship-eol.wav
some_log_value5: soft-punch.wav
some_log_value6: tube-swoosh.wav
some_log_value7: whoosh.wav
